### ISSUE TITLE
Can't install on laravel 8

### ISSUE THREAD

**Issue by xunra** [Vinelab/tracing-laravel#22]
illuminate/bus has no 8 and up required making composer install fail.

**Comment by adiachenko** [comment]
Yes, indeed. Looks like Laravel 8 upgrade has been botched, apologies for the inconvenience. 

We pushed a new version [v1.3.2](https://github.com/Vinelab/tracing-laravel/releases/tag/v1.3.2) that should address these issues. Let me know if anything else pops up. Have a nice day.
