### ISSUE TITLE
How to got json detail for rootSpan after finish?

### ISSUE THREAD

**Issue by emildd** [Vinelab/tracing-laravel#24]
how to get the traceId json result after $span->finish() ?

**Comment by adiachenko** [comment]
It may help if you provide more details on what you're trying to achieve.

If you mean to get the underlying span context, you can do that by doing something like:

```
$traceContext = $span->getContext();

// Get the underlying Zipkin span context
$traceContext->getRawContext()
``` 

This will give you access to a bunch of low-level instrumentation methods like retrieving the trace ID. 

As for getting a serialized JSON representation of the finished span, I don't think you can do that unless you [hook into  reporter yourself](https://github.com/Vinelab/tracing-laravel/blob/master/tests/Zipkin/TracerTest.php#L33) like in tests here. However, you shouldn't have the need for that normally.

**Comment by emildd** [comment]
thankyou @adiachenko
