### ISSUE TITLE
Lumen Support

### ISSUE THREAD

**Issue by wlzch** [Vinelab/tracing-laravel#30]
I'm trying to use this package on Lumen 8.0 but I'm getting a lot of missing function or method errors. Is it possible to add support for Lumen? Thank you.

**Comment by Mulkave** [comment]
@wlzch could you please help by sending a trace of the methods/errors you got?

**Comment by adiachenko** [comment]
@wlzch Sorry for the wait. We don't use Lumen ourselves so this was kinda on the back-burner for a while.

Lumen support is coming, albeit with some limitations. See #35 for more details.
