### ISSUE TITLE
Lumen with Vinelab/tracing-laravel plugin raised error

### ISSUE THREAD

**Issue by sergeynilov** [Vinelab/tracing-laravel#39]
Trying to add logger tool 
https://github.com/Vinelab/tracing-laravel#usage-with-lumen

to lumen app and I followed all steps under “Usage With Lumen” section.
Running request I got error :

     "message": "Call to undefined method Laravel\\Lumen\\Application::terminating()",
        "exception": "Error",
        "file": "/mnt/_work_sdb8/wwwroot/LumenProjects/PublishPagesAPI/vendor/vinelab/tracing-laravel/src/TracingServiceProvider.php",
        "line": 55,
        "trace": [
            {
                "file": "/mnt/_work_sdb8/wwwroot/LumenProjects/PublishPagesAPI/vendor/illuminate/container/BoundMethod.php",
                "line": 36,
                "function": "boot",
                "class": "Vinelab\\Tracing\\TracingServiceProvider",
                "type": "->"
            },
            {
                "file": "/mnt/_work_sdb8/wwwroot/LumenProjects/PublishPagesAPI/vendor/illuminate/container/Util.php",
                "line": 40,
                "function": "Illuminate\\Container\\{closure}",
                "class": "Illuminate\\Container\\BoundMethod",
                "type": "::"
            },
            {
                "file": "/mnt/_work_sdb8/wwwroot/LumenProjects/PublishPagesAPI/vendor/illuminate/container/BoundMethod.php",
                "line": 93,
                "function": "unwrapIfClosure",
                "class": "Illuminate\\Container\\Util",
                "type": "::"
            },
            {
                "file": "/mnt/_work_sdb8/wwwroot/LumenProjects/PublishPagesAPI/vendor/illuminate/container/BoundMethod.php",
                "line": 37,
                "function": "callBoundMethod",
                "class": "Illuminate\\Container\\BoundMethod",
                "type": "::"
            },
            {
                "file": "/mnt/_work_sdb8/wwwroot/LumenProjects/PublishPagesAPI/vendor/illuminate/container/Container.php",
                "line": 653,
                "function": "call",
                "class": "Illuminate\\Container\\BoundMethod",
                "type": "::"
            },
            {
                "file": "/mnt/_work_sdb8/wwwroot/LumenProjects/PublishPagesAPI/vendor/laravel/lumen-framework/src/Application.php",
                "line": 277,
                "function": "call",
                "class": "Illuminate\\Container\\Container",
                "type": "->"
            },
            {
                "file": "/mnt/_work_sdb8/wwwroot/LumenProjects/PublishPagesAPI/vendor/laravel/lumen-framework/src/Application.php",
                "line": 262,
                "function": "bootProvider",
                "class": "Laravel\\Lumen\\Application",
                "type": "->"
            },
            {
            
    I upgrated all packages in my composer.json :
    {
        "name": "laravel/lumen",
        "description": "The Laravel Lumen Framework.",
        "keywords": ["framework", "laravel", "lumen"],
        "license": "MIT",
        "type": "project",
        "require": {
            "php": "^7.3|^8.0",
            "anik/form-request": "^4.3",
            "cviebrock/eloquent-sluggable": "^8.0.8",
            "dusterio/lumen-passport": "^0.3.4",
            "flipbox/lumen-generator": "^8.2.2",
            "illuminate/mail": "^8.70.2",
            "illuminate/notifications": "^8.70.2",
            "intervention/image": "^2.7.0",
            "laravel/lumen-framework": "^8.3.1",
            "league/flysystem": " ~1.1.5",
            "openzipkin/zipkin": "^2.0.2",
            "vinelab/tracing-laravel": "^2.0.2"
        },
        "require-dev": {
            "barryvdh/laravel-debugbar": "^3.6.4",
            "fakerphp/faker": "^1.16.0",
            "mockery/mockery": "^1.4.4",
            "phpunit/phpunit": "^9.5.10"
        },
        "autoload": {
            "files": [
                "app/library/helper.php"
            ],
            "psr-4": {
                "App\\": "app/",
                "Database\\Factories\\": "database/factories/",
                "Database\\Seeders\\": "database/seeders/"
            }
        },
        "autoload-dev": {
            "classmap": [
                "tests/"
            ]
        },
        "config": {
            "preferred-install": "dist",
            "sort-packages": true,
            "optimize-autoloader": true
        },
        "minimum-stability": "dev",
        "prefer-stable": true,
        "scripts": {
            "post-root-package-install": [
                "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
            ]
        }
    }

How this error can be fixed?

Thanks!

**Comment by adiachenko** [comment]
@sergeynilov Hi! Thx for expressing the interest in our package.

You can use the [RC version](https://github.com/Vinelab/tracing-laravel/releases) temporarily to resolve this issue (e.g. v2.1.0-rc5). Simply lock it down in composer.json.

Latest stable release from August doesn't support Lumen for now. We're waiting for one of the upstream dependencies to upgrade for v2.1.0 (that also introduces PHP 8 support).
